services:
  reverse-proxy:
    image: nginx:1.29.5-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/snapforyou.cloud.pem:/etc/ssl/certs/snapforyou.cloud.pem:ro
      - ./nginx/ssl/snapforyou.cloud.key:/etc/ssl/private/snapforyou.cloud.key:ro

  backend:
    image: rhlanfwlghks/jjigeojulge-server:latest
    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    expose:
      - 8080
    networks:
      - jjigeo-network
    
    volumes:
      - ./logs:/app/.logs
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /aws/ec2/jjigeojulge-server
        awslogs-create-group: "true"
        awslogs-multiline-pattern: '^\d{4}-\d{2}-\d{2}'

  redis:
    image: redis:7.2-alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - jjigeo-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

networks:
  jjigeo-network:
    driver: bridge
